# Generated by Django 2.0 on 2018-01-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-episode', '-date']},
        ),
        migrations.AddField(
            model_name='item',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sources',
            field=models.TextField(blank=True),
        ),
    ]
