# Generated by Django 2.0 on 2018-01-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180107_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='raw_images',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='references',
            new_name='raw_references',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sources',
            new_name='raw_sources',
        ),
    ]
