# Generated by Django 2.0 on 2018-01-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caster',
            name='kamioshi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='caster',
            name='oshi_current',
            field=models.CharField(blank=True, max_length=255, verbose_name='Current Favorites'),
        ),
        migrations.AlterField(
            model_name='caster',
            name='oshi_overall',
            field=models.CharField(blank=True, max_length=255, verbose_name='All-Time Favorites'),
        ),
    ]
