# Generated by Django 2.0 on 2018-01-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casters', '0002_auto_20180115_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='caster',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
