# Generated by Django 2.0 on 2018-01-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
    ]
