# Generated by Django 2.0 on 2018-01-15 01:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0002_auto_20180107_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('game', 'Game'), ('talk', 'Talk')], default='activity', max_length=8)),
                ('description', models.TextField()),
            ],
        ),
    ]
