# Generated by Django 2.0 on 2018-01-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_corner'),
    ]

    operations = [
        migrations.AddField(
            model_name='corner',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
