# Generated by Django 2.0 on 2018-01-24 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('episodes', '0004_corner_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('performer', models.CharField(max_length=60)),
                ('song', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('embed_url', models.URLField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episodes.Episode')),
            ],
        ),
    ]
