# Generated by Django 2.0 on 2018-01-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
